import { StyleSheet, Dimensions } from "react-native";

const winWidth = Dimensions.get("screen").width;
const winHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  postContainer: {
    overflow: "hidden",
    marginBottom: 15,
    backgroundColor: "#ffffff",
  },
  top: {
    backgroundColor: "#ffffff",
    width: "100%",
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  profileBox: {
    width: "20%",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  profileContainer: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    borderWidth: 2,
    borderColor: "#dddddd",
    backgroundColor: "#111111",
    overflow: "hidden",
  },
  topNameContainer: {
    width: "80%",
    padding: 10,
  },
  nameTxt: {
    fontWeight: "700",
  },
  body: {
    width: "100%",
    // height: 500,
    // maxHeight: 500,
  },
  postTextContainer: {
    padding: 15,
  },
  postText: {
    textAlign: "justify",
  },
  textEnd: {
    color: "#999999",
    backgroundColor: "#f2f2f2",
    padding: 3,
    borderRadius: 4,
    width: 80,
    textAlign: "center",
    fontSize: 10,
  },
  imagesPostContainer: {
    width: winWidth,
    height: 400,
    flexDirection: "row",
    flexWrap: "wrap",
    maxHeight: 400,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  imageBox1: {
    width: "100%",
    height: 400,
    backgroundColor: "#333",
  },
  imageBox2: {
    width: "50%",
    height: 400,
    backgroundColor: "#333",
  },
  imageBox3: {
    width: "33%",
    height: 400,
    backgroundColor: "#333",
  },
  imageBox4: {
    width: "50%",
    height: 200,
    backgroundColor: "#333",
    overflow: "hidden",
  },
  imageBox5: {
    width: "50%",
    height: 200,
    backgroundColor: "#333",
    overflow: "hidden",
  },
  overlayPic: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: "50%",
    height: "50%",
    backgroundColor: "rgba(255,255,255, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  bottom: {
    width: "100%",
    // height: 50,
    borderColor: "#d9d9d9",
    borderWidth: 0.5,
    backgroundColor: "#ffffff",
  },
  botTopPart: {
    width: "100%",
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  botBottomPart: {
    width: "100%",
    height: 50,
    borderTopWidth: 1,
    borderTopColor: "#d9d9d9",
    flexDirection: "row",
    alignItems: "center",
  },
  botProfileContainer: {
    width: "15%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
  },
  profileCircle: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    borderWidth: 2,
    borderColor: "#cccccc",
    overflow: "hidden",
  },
  commentClick: {
    width: "85%",
    height: "100%",
    padding: 5,
  },
  commentInputBox: {
    borderWidth: 1,
    borderColor: "#bfbfbf",
    borderRadius: 45,
    height: "100%",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 20,
  },
  // ================= Modal Image =================
  mainModalContainer: {
    backgroundColor: "#e6e6e6",
    width: "100%",
    height: "100%",
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
  },
  modalTop: {
    width: "100%",
    backgroundColor: "#d9d9d9",
    padding: 10,
    flexDirection: "row",
  },
  inputCommentContainer: {
    width: "100%",
    height: 50,
    borderTopWidth: 1,
    borderTopColor: "#bbbbbb",
    padding: 5,
    alignItems: "center",
    flexDirection: "row",
  },
  commentTextInput: {
    borderWidth: 0.5,
    height: "100%",
    padding: 5,
    borderRadius: 5,
    color: "#111111",
    width: "90%",
    borderColor: "#cccccc",
  },
  commentContainer: {
    width: "100%",
    backgroundColor: "#dddddd",
    padding: 10,
    marginVertical: 10,
  },
  top: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  circleContainer: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    borderWidth: 2,
    borderColor: "#cccccc",
    marginRight: 10,
    overflow: "hidden",
  },
  commentName: {
    fontWeight: "700",
  },
  bot: {
    width: "90%",
    alignSelf: "flex-end",
  },
  mainModalContainerBlack: {
    backgroundColor: "#111111",
    width: "100%",
    height: "100%",
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
  },
  topCloseIcon: {
    width: "100%",
    padding: 10,
  },
  modalImageCon: {
    width: winWidth,
    height: winHeight * 0.4,
    alignSelf: "center",
    overflow: "hidden",
  },
  noComment: {
    alignSelf: "center",
    color: "#999999",
    marginTop: 300,
  },
  sendCommentIconContainer: {
    width: "10%",
    alignItems: "center",
    justifyContent: "center",
  },
});

export default styles;
